config/routes.rb
Rails.application.routes.draw do
  get 'airlines/index'
  devise_for :users

  # front page
  root :to => 'home#index'
  get 'home/index'
  get 'portfolio', :to => "portfolio#index"
  
  get '/admin', :to => "admin#index"
  get '/admin/blogs', :to => "admin_blog#index"
  get '/admin/images', :to => "admin_images#index"
  get '/admin/tags', :to => "admin_tags#index"
  get '/admin/users', :to => "admin_users#index"
  get '/admin/products', :to => "admin_products#index"
  get '/admin/products/:id', :to => "admin_products#detail"
  post '/admin/product_create', :to => "admin_products#create"
  post '/admin/product_info', :to => "admin_products#info"
  get 'admin_users/index'
  get 'admin_tags/index'
  
  # airlines page
  get '/airlines', :to => 'airlines#index'
  get '/airlines/:slug', :to => 'airlines#show'

  # name space for api
  namespace :api do
    namespace :v1 do
      resources :airlines, params: :slug
      resources :reviews
    end
  end
  
  # redirect to home index any stray requests not declared in the route
  get '*path', to: 'home#index', via: :all
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/airline.rb
class Airline < ApplicationRecord
    has_many :reviews, -> { order 'id DESC'} 

    # call this before creation is done -> this will automatically trigger the sluggify
    before_create :slugify

    def slugify
        self.slug = name.parameterize
    end
    
    def avg_score
        score = reviews.average(:score)
        if score 
            return score.round(2).to_f
        else
            return 0
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donator.rb
class Donator < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
    has_one_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
end

app/models/product_memo.rb
class ProductMemo < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :airline
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_donation_stat.rb
class UserDonationStat < ApplicationRecord
end

app/helpers/admin_base_helper.rb
module AdminBaseHelper
end

app/helpers/admin_blog_helper.rb
module AdminBlogHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_tags_helper.rb
module AdminTagsHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/donators_helper.rb
module DonatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/admin_partials/_modal.html.erb
<!-- Logout Modal-->
<div class="modal fade" id="newTodoModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">NEW TODO</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group col-sm-12">
                    <input 
                        type="text" 
                        class="form-control form-control-user" 
                        id="exampleInputEmail" 
                        aria-describedby="emailHelp" 
                        v-model = "todo.title"
                        placeholder="Title">
                </div>
                <div class="form-group col-sm-12">
                    <textarea 
                        class="form-control form-control-user" 
                        id="exampleInputEmail" 
                        aria-describedby="emailHelp"
                        rows=5 
                        v-model = "todo.content"
                        placeholder="Content"></textarea>
                    <input type="hidden" v-model = "todo.id">
                </div>
            </div>
            <div class="modal-footer">
                <button 
                    class="btn btn-secondary" 
                    type="button" 
                    data-dismiss="modal">Cancel</button>
                <a 
                    v-on:click="createNewTodo($event)"
                    class="btn btn-primary" 
                    href="javascript:void(0);">
                    <span v-if="todo.id == ''">ADD</span>    
                    <span v-if="todo.id">UPDATE</span>    
                </a>
            </div>
        </div>
    </div>
</div>

app/views/admin_partials/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email %></span>
                <i class="fas fa-fw fa-caret-down"></i>
            </a>
            
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <%= link_to edit_user_registration_path, :class => "dropdown-item" do %>
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                <% end %>
                <%= button_to destroy_user_session_path, method: :delete, :class => "dropdown-item" do%>
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                <% end %>
            </div>
        </li>
    </ul>
</nav>

app/views/admin_partials/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-cat"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Silverius Codes Admin</div>
    </a>
    
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    
    <!-- Nav Item - Dashboard -->
    <li class="nav-item <%= (@page_name == "blog") ? "active" : "" %>" style="display: none;">
        <%= link_to admin_blogs_path, :class => "nav-link #{(@page_name == "blog") ? "active" : ""}" do %>
            <i class="fas fa-fw fa-blog"></i>
            <span>Blogs</span></a>
        <% end %>
    </li>
    <li class="nav-item <%= (@page_name == "setting_products") ? "active" : "" %>">
        <%= link_to admin_products_path, :class => "nav-link #{(@page_name == "setting_products") ? "active" : ""}" do %>
            <i class="fas fa-users"></i>&nbsp;Products
        <% end %>
    </li>

    <!-- Heading -->
    <div class="sidebar-heading" style="display: none;">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li 
        style="display: none"
        class="nav-item <%= (@collapse_name == "settings") ? "active" : "" %>">
        <a 
            class="nav-link collapsed" 
            href="javascript:void(0)" 
            data-toggle="collapse" 
            data-target="#collapse_settings"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-cogs"></i>
            <span>Settings</span>
        </a>
        <div 
            id="collapse_settings" 
            class="collapse" 
            aria-labelledby="headingPages" 
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <%= link_to admin_images_path, :class => "collapse-item #{(@page_name == "setting_images") ? "active" : ""}" do %>
                    <i class="fas fa-images"></i>&nbsp;Images
                <% end %>
                <%= link_to admin_tags_path, :class => "collapse-item #{(@page_name == "setting_tags") ? "active" : ""}" do %>
                    <i class="fas fa-tags"></i>&nbsp;Tags
                <% end %>
                <%= link_to admin_products_path, :class => "collapse-item #{(@page_name == "setting_products") ? "active" : ""}" do %>
                    <i class="fas fa-users"></i>&nbsp;Products
                <% end %>
            </div>
        </div>
    </li>
</ul>
<!-- End of Sidebar -->

<!-- when the page is ready -->

<script>
var current_collapse_name = "<%= @collapse_name %>";
$(function(){
    // if (current_collapse_name.trim().length != 0) {
    //     $('#collapse_' + current_collapse_name).collapse('toggle')
    // }
});
</script>